image: node:8.15

variables:
  CI: "true"
  DOCKER_DRIVER: overlay2
  NODE_ENV: test

cache:
  paths:
    - node_modules
    - build

stages:
  - install
  - deploy

install:
  stage: install
  artifacts:
    paths:
      - node_modules
      - build
    expire_in: 1 day
  retry: 2
  script:
    - yarn install
    - yarn build
